In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
categories = ['Red', 'Green', 'Blue']

In [3]:
encoder = OneHotEncoder()

In [6]:
# Fit and transform the data
encoded_data = encoder.fit_transform(np.array(categories).reshape(-1, 1))

In [7]:
# Convert sparse matrix to dense array (if needed)
encoded_data_array = encoded_data.toarray()

In [8]:
print(encoded_data_array)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
categories = ['Small', 'Medium', 'Large']

In [11]:
# Initialize the LabelEncoder
encoder = LabelEncoder()

In [12]:
# Fit and transform the data
encoded_data = encoder.fit_transform(categories)

In [13]:
print(encoded_data)

[2 1 0]
